document:
  name: Linee guida per la digitalizzazione del patrimonio culturale
  description: |
      Le Linee guida 1 hanno l'obiettivo di definire approcci e procedure per la creazione, la metadatazione e l’archiviazione degli oggetti digitali.

  tags:
      - patrimonio culturale digitale
      - digitalizzazione
      - digital transformation
